/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-09-07

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include <string.h>
#include "stm32l0xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

uint8_t uart_rx(void){
	while(!(USART1->ISR & USART_ISR_RXNE)); // wait for data
	return (char)(USART1->RDR); // read
}

void uart_tx(char txdata){
	while(!(USART1->ISR & USART_ISR_TXE)); // wait
	USART1->TDR = txdata; // send
}

void send_uart(char *buffer){

	char sent_char = buffer[0];
	int i = 0;
	while(sent_char != '\0'){
		sent_char = buffer[i];
		uart_tx(sent_char);
		i++;
	}
}

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	SystemCoreClockUpdate();

	// Enable peripheral clock for USART1, APB2
	RCC->APB2ENR |= RCC_APB2ENR_USART1EN;

	// ...and for GPIOB
	RCC->IOPENR |= RCC_IOPENR_GPIOBEN;

	// Mux PB6 to AF0 (USART1TX) and set to Alt. function
	GPIOB->AFR[0] = (GPIOB->AFR[0] & ~(0xf000000));
	GPIOB->MODER = (GPIOB->MODER & ~(GPIO_MODER_MODE6)) | (GPIO_MODER_MODE6_1);

	// Mux PB7 to AF0 (USART1RX) and set to Alt. function
	GPIOB->AFR[0] = (GPIOB->AFR[0] & ~(0xf0000000));
	GPIOB->MODER = (GPIOB->MODER & ~(GPIO_MODER_MODE7)) | (GPIO_MODER_MODE7_1);

	// Baud rate 9600
	USART1->BRR = SystemCoreClock / 9600;

	// Enable, no parity, 8 data bits, etc
	USART1->CR1 |= USART_CR1_TE | USART_CR1_RE | USART_CR1_UE;

	char buffer[32] = "";

	char weclome[] = "\r\nWelcome!\r\n";

	send_uart(weclome);


	/* TODO - Add your application code here */
	while (1)
	{
		int last_input = 0;
		uint8_t character = 1;

		while(character != '\r'){
			character = uart_rx();
			buffer[last_input] = character;

			last_input++;
			if(last_input > 31){
				last_input = 0;
			}
		}

		char hello_string[] = "hello!\r";

		if(strcmp(buffer, hello_string) == 0){
			char output_buffer[] = "Good bye!";
			send_uart(output_buffer);
		}

	}

	return 0;
}
