/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-09-07

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "stm32l0xx.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

void
delay_systicks(uint32_t ticks) {
	//disable systick
	SysTick->CTRL = 0;

	//count from (ticks -1) to 0 (i.e. ticks cycles)
	SysTick->LOAD = ticks - 1;

	//clear current value and count flag
	SysTick->VAL = 0;

	//enable systick timer with processor clock
	SysTick->CTRL = (1 << 2) | (1 << 0);

	//wait until count flag is set
	while((SysTick->CTRL & (1 << 16)) == 0);

	//disable systick
	SysTick->CTRL= 0;
}

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	int wait_time = 50000;

	// Enable peripheral clock for GPIOA and GPIOB
	RCC->IOPENR |= (RCC_IOPENR_GPIOAEN | RCC_IOPENR_GPIOBEN);

	// General purpose output mode for LED, PA5, PA4, PA3
	GPIOA->MODER = (GPIOA->MODER & ~(GPIO_MODER_MODE5 | GPIO_MODER_MODE4 | GPIO_MODER_MODE3)) | (GPIO_MODER_MODE5_0 | GPIO_MODER_MODE4_0 | GPIO_MODER_MODE3_0);

	//Set PB3 and PB7 to inputs
	GPIOB->MODER = (GPIOB->MODER & ~(GPIO_MODER_MODE3 | GPIO_MODER_MODE7));

	//Pull-up PB3
	GPIOB->PUPDR = ((GPIOB->PUPDR & ~(GPIO_PUPDR_PUPD3)) | GPIO_PUPDR_PUPD3_0);

	//Pull-down PB7
	GPIOB->PUPDR = ((GPIOB->PUPDR & ~(GPIO_PUPDR_PUPD7)) | GPIO_PUPDR_PUPD7_1);

	while(1){

		if((!(GPIOB->IDR & GPIO_IDR_ID3))&&((GPIOB->IDR & GPIO_IDR_ID7))){ //Both are pressed!
			GPIOA->BSRR = GPIO_BSRR_BS_5 + GPIO_BSRR_BS_4 + GPIO_BSRR_BS_3;
			delay_systicks(wait_time);
		}
		else if(!(GPIOB->IDR & GPIO_IDR_ID3)){ //If PB3 is low. button pressed
			GPIOA->BSRR	= GPIO_BSRR_BS_5;
			delay_systicks(wait_time);
		}
		else if((GPIOB->IDR & GPIO_IDR_ID7)){ //If PB7 is high. button pressed
			GPIOA->BSRR = GPIO_BSRR_BS_5 + GPIO_BSRR_BS_4;
			delay_systicks(wait_time);
		}

		GPIOA->BSRR = GPIO_BSRR_BR_5 + GPIO_BSRR_BR_4 + GPIO_BSRR_BR_3;
		delay_systicks(wait_time);
	}
	return 0;
}
